# This workflow builds and tests a .NET solution located in a sub-folder.
# It's triggered on pushes and pull requests to the 'main' branch.

name: Build and Test .NET Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Set a default working directory for all subsequent steps in this job
    defaults:
      run:
        working-directory: ./Contract_Monthly_Claim_System

    steps:
    # 1. Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up the specified .NET SDK version
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 3. Cache NuGet packages to speed up subsequent builds
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # 4. Restore dependencies for the entire solution
    # This now runs inside the './Contract_Monthly_Claim_System' directory
    - name: Restore dependencies
      run: dotnet restore Contract_Monthly_Claim_System.sln

    # 5. Build the solution in Release configuration
    - name: Build solution
      run: dotnet build Contract_Monthly_Claim_System.sln --configuration Release --no-restore

    # 6. Run tests and collect code coverage
    # The results-directory will now be created inside the working directory
    - name: Run tests with code coverage
      run: dotnet test Contract_Monthly_Claim_System.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    # 7. Upload the coverage report as an artifact
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        # The path is now relative to the root, so we specify the full path
        path: ./Contract_Monthly_Claim_System/coverage/
```

### Key Changes and Why They Work

1.  **`defaults` Block:** I've added a `defaults` section at the job level:
    ```yaml
    defaults:
      run:
        working-directory: ./Contract_Monthly_Claim_System
    

